import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <link
          rel="stylesheet"
          as="style"
          crossOrigin="anonymous"
          href="https://cdn.jsdelivr.net/npm/pretendard/dist/web/static/pretendard.css"
        />
      </head>
      <body className="min-h-screen flex flex-col">
        <div className="flex flex-col mx-auto md:container md:min-h-[calc(100dvh-358px-64px)]">
          <Header />
          <main className="pb-13 pt-[24px] md:py-[40px] lg:py-[80px]">
            {children}
          </main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
